vmware/kube-fluentd-operator

README.md, log-router/Chart.yaml, log-router/templates/daemonset.yaml, log-router/values.yaml
I add parameter 'updateStrategy' to helm chart for daemonset.
=> Add parameter 'updateStrategy' to helm chart for daemonset

base-image/Dockerfile
Im using this gem for extra metadata in my logs. I hope you find it useful too
=> Include fluent-plugin-kubernetes_sumologic plugin

README.md, base-image/Dockerfile
This has been tested working in K8s.
=> Add cloudwatch-logs plugin

base-image/Dockerfile
Please refer to this issue, #69 , for more details.
=> Removed root user as fluentd has Uid. Removed libjemalloc install due to the base image installing it.

base-image/Dockerfile
This PR adds the Azure Log Analytics plugin to send logs to Azure Log Analytics.
=> Add Azure Log Analytics plugin

CHANGELOG.md, README.md
Signed-off-by: Dimal Baby <dbaby@vmware.com>
=> Update release note(v1.12.0)

.github/workflows/build-workflow.yaml
* Added the .github/workflows directory with a simple build workflow.
=> Adding github workflows

.github/workflows/build-workflow.yaml, README.md
- Update the doc
- Update the new chart location in build-workflow
Signed-off-by: Dimal Baby <dbaby@vmware.com>
=> Doc update for v1.13.0 release

.github/workflows/build-workflow.yaml
Fix helm failures with old version of helm
=> fix: fix helm chart deprecated endpoints

.github/workflows/build-workflow.yaml
Signed-off-by: Vivek Singh <svivekkumar@vmware.com>
=> Update helm to helm3 in ci

CHANGELOG.md
- update changelogs file for v1.14.0-beta.3
=> chore: update changelogs for v1.14.0-beta.3

config-reloader/datasource/kubedatasource/fluentdconfig/crd/crd.go, kubectl/README.md, kubectl/crd.yaml, kubectl/manifests.yaml
- adding example manifests files for kubectl apply
- resolves #188
=> feat(kubectl): add manifests for kubectl install

CHANGELOG.md, README.md
- update changelogs for v1.14.0 release
- update plugin versions in README
- closes #198
=> chore: update changelogs for v1.14.0

README.md
- add more detailed build instructions
=> chore(docs): add better build instructions

base-image/Dockerfile
- add findutils for validation script instructions
- fixes #140
=> fix(base-image): add findutils for validate script

README.md, charts/log-router/Chart.yaml, charts/log-router/templates/daemonset.yaml, charts/log-router/values.yaml, config-reloader/Makefile, config-reloader/config/config.go, config-reloader/config/config_test.go, config-reloader/generator/generator.go, config-reloader/processors/destinations.go, config-reloader/processors/processor.go
- add custom --buffer-mount-folder flag on reloader
- resolves #183
=> feat(reloader): add custom --buffer-mount-folder option

config-reloader/config/config.go
- fix buffer path name logic mistake
=> fix(config.go): fix buffer path name check

base-image/Gemfile
- upgrade to fluentd v1.12.3 with latest `in_tail` fixes
- https://github.com/fluent/fluentd/issues/3355
- https://github.com/fluent/fluentd/pull/3328
- Changelog: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1123---20210423
=> feat(fluentd): upgrade fluentd to v1.12.3

CHANGELOG.md, README.md
- update gem list, changelog, and helm command for v1.14.1
=> docs(readme): update changelogs for v1.14.1

README.md, charts/log-router/templates/daemonset.yaml, config-reloader/config/config.go, config-reloader/config/config_test.go
- fix the buffermount helm logic
=> fix(charts): fix bufferMountFolder logic in ds

CHANGELOG.md, README.md, config-reloader/config/config.go
- update gem list, changelog, and helm command for v1.15.0
- fix lint error in config.go
=> docs(readme): update changelogs for v1.15.0

base-image/Dockerfile
- clear out tdnf cache around `tdnf upgrade` command
=> fix(Dockerfile): add tdnf clean commands

CHANGELOG.md, README.md
- update gem list, changelog, and helm command for v1.15.1
=> docs(readme): update changelogs for v1.15.1

config-reloader/datasource/kube_informer.go
- use update instead of patch for status annotation on namespace
- handle removing of annotation if status is error status is blank
=> fix(reloader): use update for status annotation

CHANGELOG.md, README.md
- update gem list, changelog, and helm command for v1.15.2
=> docs(readme): update changelogs for v1.15.2

config-reloader/config/config.go, config-reloader/controller/controller.go, config-reloader/controller/updater.go, config-reloader/datasource/datasource.go, config-reloader/datasource/fake.go, config-reloader/datasource/fs.go, config-reloader/datasource/kube_informer.go, config-reloader/datasource/kubedatasource/configmap.go, config-reloader/datasource/kubedatasource/fluentdconfig.go, config-reloader/datasource/kubedatasource/fluentdconfig/crd/crd.go, config-reloader/datasource/kubedatasource/kubedatasource.go, config-reloader/datasource/kubedatasource/migrationmode.go, config-reloader/fluentd/reloader.go, config-reloader/fluentd/reloader_test.go, config-reloader/fluentd/validator.go, config-reloader/fluentd/validator_test.go, config-reloader/generator/generator.go, config-reloader/main.go, config-reloader/processors/detect_exceptions_test.go, config-reloader/processors/expand_tags.go, config-reloader/processors/expand_tags_test.go, config-reloader/processors/labels.go, config-reloader/processors/thisns_test.go, config-reloader/processors/unique_rewrite_tag.go, config-reloader/processors/unique_rewrite_tag_test.go
- propogate context across child functions
- closes #249
- opens #255
=> feat(context): propagate context from main func

config-reloader/templates/fluent.conf, config-reloader/templates/kubernetes.conf, config-reloader/templates/prometheus.conf, config-reloader/templates/systemd.conf
- upgrade systemd fluentd configs based on fluentd samples
=> chore(conf): upgrade systemd fluentd configs

CHANGELOG.md, README.md
- update gem list, changelog, and helm command for v1.15.3
=> docs(readme): update changelogs for v1.15.3

README.md, base-image/Gemfile, base-image/Gemfile.lock
- resolves #266 temporarily
- deprecating the splunk plugins because of issues
=> fix(plugins): remove splunk plugins for #266

CHANGELOG.md, README.md
- update gem list, changelog, and helm command for v1.16.0
=> docs(readme): update changelogs for v1.16.0

README.md
- small minor patch version needs to be released
=> chore(docs): update docs for v1.16.1 release

CHANGELOG.md
- update gem list, changelog, and helm command for v1.16.1
=> docs(readme): update changelogs for v1.16.1

CHANGELOG.md, CONTRIBUTING.md, README.md
- update gem list, changelog, and helm command for v1.16.2
=> docs(readme): update changelogs for v1.16.2

.github/workflows/build-workflow.yaml, .github/workflows/release-workflow.yaml, config-reloader/Makefile
- Add workload for release creation
- Add docker login for dockerhub
=> chore: add pipeline for release builds

CHANGELOG.md, README.md
- docs(readme): update changelogs for v1.16.3
=> docs(readme): update changelogs for v1.16.3

CHANGELOG.md, README.md
- docs(readme): update changelogs for v1.16.4
=> docs(readme): update changelogs for v1.16.4

LICENSE, base-image/Dockerfile, config-reloader/Dockerfile, config-reloader/validate-from-dir.sh
- update ruby to 2.7.6
- update cgi to 0.1.1
- remove unneeded cache files
Signed-off-by: Brian Davis <dbrian@vmware.com>
=> fix: update ruby to 2.7.6

CHANGELOG.md, README.md
update readme and changelogs for new version
=> docs(readme): update changelogs for v1.16.5

CHANGELOG.md, README.md
update readme and changelogs for new version
=> docs(readme): update changelogs for v1.16.6

CHANGELOG.md, README.md
=> docs(readme): update changelogs for v1.16.7

base-image/Gemfile, base-image/Gemfile.lock
update the dependency to upgrade fluentd to v1.15.0. tests have been done on local.
=> update fluentd to v1.15.0

base-image/Gemfile, base-image/Gemfile.lock
Install throttle plugin in base image
VDPENG-10966
=> feat: add support for throttle plugin

config-reloader/templates/prometheus.conf
Add missing prometheus metrics for monitoring
=> feat: add missing prometheus metrics

.github/workflows/release-workflow.yaml
Generate release just after publish images
=> feat: generate release after publish images

.github/workflows/build-workflow.yaml, config-reloader/controller/controller.go, config-reloader/controller/updater.go, config-reloader/fluentd/validator.go, config-reloader/generator/generator.go, config-reloader/util/util.go, config-reloader/util/util_test.go
* Create interface for controller
* Controller private variables
* Move validator function 
=> feat: golang refactor for config-reloader

.github/workflows/build-workflow.yaml
Change actions trigger to push and pull requests
=> feat: change actions trigger

config-reloader/datasource/fake.go, config-reloader/datasource/fs.go, config-reloader/datasource/kube_informer.go
Move constructor to top in the file
=> feat: move constructor to the top

CHANGELOG.md, README.md
=> docs(readme): update changelogs for v1.16.8

CHANGELOG.md, README.md
=> docs: prepare release v1.17.0

base-image/Gemfile, base-image/Gemfile.lock
Increase loginsight plugin version with new performance improvements
=> feat: increase loginsight plugin version

CHANGELOG.md, README.md
=> docs: generate new release

LICENSE, README.md, header.txt
- remove license block from readme
- update license file
- remove header.txt
=> fix: update license and remove from README

base-image/Dockerfile, base-image/plugins/parser_kubernetes.rb, base-image/plugins/parser_multiline_kubernetes.rb
- do not download plugins from upstream
=> fix: do not download plugins and just include them

config-reloader/datasource/kube_informer.go, config-reloader/generator/generator.go, config-reloader/validate-from-dir.sh
=> feat: re-add validator command

.github/workflows/release-workflow.yaml, config-reloader/validate-from-dir.sh
Publish latest image with release
=> feat: publish latest image

base-image/plugins/filter_dedot.rb
Add de_dot plugin to use if need it
=> feat: add de_dot plugin

base-image/Dockerfile
Fix correct dockerfile for base-image
=> fix: correct dockerfile

CHANGELOG.md, README.md
=> docs: prepare release 1.17.6

config-reloader/datasource/kube_informer.go, config-reloader/datasource/kube_informer_test.go
Fix unable to start if mismatch tag is present in some config
=> fix: unable to start if mismatchtag in config

base-image/Gemfile, base-image/Gemfile.lock
- update lint plugin and gemfile lock
=> update lint plugin and gemfile lock

.github/workflows/build-workflow.yaml, .github/workflows/release-workflow.yaml, Dockerfile, Makefile
- add support for multiarch image
=> feat: add support for multiarch image

CHANGELOG.md, README.md
- Changelog and readme updates for v.1.18
=> docs: changelog for release v1.18
