vmware/kube-fluentd-operator

README.md, log-router/Chart.yaml, log-router/templates/daemonset.yaml, log-router/values.yaml
Hi! Here it is 😃 
I didn't update the following line in the README:
`CHART_URL='https://github.com/vmware/kube-fluentd-operator/releases/download/v1.1.0-beta-1/log-router-0.2.0.tgz'`
Since for that you need to release the chart embbeded in a .tgz (version 0.2.1)
=> Update the log-router chart to accept custom volumes

README.md, base-image/Dockerfile
This PR installs the fluent-plugin-splunkhec gem which allows for sending logs to the Splunk HTTP Event Collector.
=> Add fluent-plugin-splunkhec to base-image

README.md, base-image/Dockerfile
Installing additional output plug-ins in base image:
- plugin for Apache Kafka > 0.8
- flowcounter plugin which counts messages/bytes that matches, per minutes/hours/days
- plugin which sends events to Amazon Kinesis
- plugin for mongoDB
- plugin to handle Facebook scribed thrift protocol
- plugin for mail
- plugin for influxdb
- plugin to count the number of matched messages, and emit if exceeds the threshold
- plugin for GrowthForecast
=> Installing additional fluentd plugins in base image

README.md, log-router/Chart.yaml, log-router/templates/daemonset.yaml, log-router/values.yaml
In my use case(fluent-s3-plugin),  I need to attach the IAM role to the pod with kubernetes annotation with [kube2iam](https://github.com/jtblin/kube2iam).
So, I added annotation parameter for daemonset template.
=> Add pod annotation parameter for daemonset template

README.md, base-image/Dockerfile
AMQP plugin once again. The other version of the plugin is almost useless as it does not allow configuration of rounting_key nor handle SSL at all. We are actually using this version currently, using the other was a mistake sorry for that.
=> Install AMQP plugin

README.md, log-router/Chart.yaml, log-router/templates/daemonset.yaml, log-router/templates/secret.yaml, log-router/values.yaml
Hi.
I modified helm chart, so please check it.
- ```extraEnv```,``` extraVolumeMounts``` can be set individually for fluentd and reloader
- ```extraVolumeMounts```: When I use ```fluent-plugin-google-cloud```, it happened credential error in reloader, so I need ```extraVolumeMounts``` in reloader
- ```error=\"Could not load the default credentials. Browse to\\nhttps://developers.google.com/accounts/docs/application-default-credentials```
- ```extraEnv```:  I thought it would be useful, and added it.
- When ```env``` is updated, daemonset pods automatically update (if ```updateStrategy.type:rollingUpdate```)
- add checksum for env value to annotation
=> Some parameters of helm chart can be set in each container

config-reloader/config/config.go, config-reloader/controller/controller.go, config-reloader/datasource/datasource.go, config-reloader/datasource/kube.go, config-reloader/datasource/kube_multimap.go, log-router/templates/daemonset.yaml, log-router/values.yaml
I would like to hear your feedback on this as this feature is very needed in our environment where each service deployment (as Helm Chart) should be able to configure logging for itself. So I ve got this Idea with a new Datasource which would support that.
Datasource:
* List namespaces
* List ConfigMaps in a namespace
* Checks for Annotation presence
* If present merge configuration to per-namespace configuration
=> Multiple configmaps per namespace support

README.md, base-image/test/local.conf, config-reloader/templates/kubernetes-postprocess.conf, config-reloader/templates/systemd.conf
fluent-plugin-parser gem was overwriting filer parser syntax with that
of the 0.12 fluentd version. After this plugin is removed code must be
changed to the syntax of the newer fluentd versions.
These changes are not tested as I'm not sure what is the procedure.
=> Syntax changes due to removing of fluent-plugin-parser

README.md, log-router/values.yaml
The default docker repository in the Helm chart appears not to exist. I've also added a comment with the format of the updateStrategy field.
=> Fix default docker repository

base-image/Dockerfile
Adds the datadog output plugin to enable sending metrics to datadog.
Hope you find it useful.
=> Add fluent-plugin-datadog

config-reloader/processors/extract_plugins.go, config-reloader/processors/extract_plugins_test.go
This PR adds the ability to use the virtual plugin (https://github.com/vmware/kube-fluentd-operator#reusing-output-plugin-definitions-since-v160) in the `store` directive as part of the `copy` type. 
This allows for:
kube-system:
```
<plugin default>
...
</plugin>
```
other namespaces:
```
<match **>
@type copy
<store>
@type default
</store>
<store>
... 
</store>
</match>
```
=> Allow the use of virtual plugin in store directive

config-reloader/datasource/datasource.go, config-reloader/processors/mounted_file.go, config-reloader/processors/mounted_file_test.go
If the `volumeMount` contains a `subPath` the generated `path` points to the wrong location.
Example pod fragment:
```yaml
apiVersion: v1
kind: Pod
metadata:
name: example-pod
spec:
containers:
- name: busybox
image: busybox
volumeMounts:
- mountPath: /var/log
name: logs
subPath: path
volumes:
- name: logs
emptyDir: {}
```
This PR will fix this issue.
=> Add subPath support to mounted-file

config-reloader/templates/kubernetes.conf
Support container logs from nodes running with docker or with crio (https://cri-o.io/).
=> Add support for CRI-O format

config-reloader/processors/relabel.go, config-reloader/processors/relabel_test.go
This small enhancement allows the "relabel" processor to normalize labels
also when the "relabel" plugin is not directly placed inside a match
directive but rather placed in a store directive. This is a valid config
that could derive from the necessity of demultiplexing logs to several
pipelines that still need to perform additional processing before
reaching the output.
Previously the labels inside a store directive would not be normalized while
the corresponding labels in the label directive would. This would lead to
fluentd complaining that the non-normalized label was non-existent as it
was not able to find the corresponding label directive.
This behavior could also allow to generate unexpected results as a label created
in a store directive could be generated to match a normalized …
=> Fix labels not being rewritten in copy plugin

config-reloader/templates/kubernetes.conf
Ruby regex implementation is extremely slow without an anchor.
=> Fix slow CRI-O log parsing

config-reloader/processors/detect_exceptions_test.go, config-reloader/processors/labels.go, config-reloader/processors/labels_test.go
This fix addresses two errors in the processor that manages the `$label`
macro.
The first error occurs when a bad label is used in the configurations.
The processor detects the bad label but fails to report the error and
stop the processing, therefore the unmodified tag containing the $label
macro is delivered to the fluentd config.
The second issue is the failure of the processor to accept as valid
labels containing the `/` character, which is however not only valid,
but encouraged for example by [helm as a best practice for the
standard labels](https://helm.sh/docs/topics/chart_best_practices/labels/).
Signed-off-by: Tommaso Pozzetti <tommypozzetti@hotmail.it>
=> Fix $label processor ignoring errors and not accepting "/"

log-router/Chart.yaml, log-router/templates/daemonset.yaml
Pretty trivial but I try to keep up with Kubernetes deprecations where possible.
Remove use of deprecated DaemonSet API:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
=> Change daemonset to apps/v1 and fix validity

config-reloader/controller/controller.go, config-reloader/controller/updater.go, config-reloader/datasource/kube_informer.go
Fluentd configurations are usually required to be reloaded as soon as
possible after they have been deployed in the ConfigMap as the corresponding
applications might start logging right away and until such configurations
are deployed, all logs might not get parsed correctly.
*kube-fluentd-operator* can be configured to reload and calculate new configs
after a given interval regardless of changes that have happened in the
cluster. However, this system can become inefficient, especially for large
clusters with many configurations to load, parse and rewrite. An interval
which is too small leads to configurations being available almost instantly
after the ConfigMap is deployed, but when no changes to such configurations
happen for a long time, it leads to a lot of useless recalculations. On …
=> Introduce a more efficient event-triggered reload system

config-reloader/config/config.go, config-reloader/generator/generator.go, config-reloader/processors/detect_exceptions_test.go, config-reloader/processors/expand_tags.go, config-reloader/processors/expand_tags_test.go, config-reloader/processors/labels_test.go, config-reloader/processors/processor.go, config-reloader/processors/relabel_test.go, config-reloader/processors/thisns.go, config-reloader/processors/thisns_test.go, log-router/templates/daemonset.yaml, log-router/values.yaml
A valid Fluentd configuration file allows to specify match patterns of
the type "k.{a,b}.\*\*" that are expanded to match both tag "k.a.\*\*" and
tag "k.b.\*\*" and processed with the same set of rules. Furthermore,
several tags can be listed in the match pattern separated by a space to
provide an expression that will match any of the tags. Supporting such
tag expansion allows to consistently reduce the number of equivalent
rules that need to be provided in the configuration file, especially
for complex systems that contain several log parsing pipelines. Finally,
support for such feature also reduces the risk for configuration errors
typical of the copy-paste pattern that needs to be adopted when such
expansion is performed by the user.
By adding this new processor to the default …
=> Add new processor to support tag expansion

README.md, log-router/templates/daemonset.yaml, log-router/values.yaml
This makes the default configmap configurable through the helm chart
=> feature: Make default configmap configurable through helm

config-reloader/generator/generator.go
This fix addresses the case in which a processor returns an error during
the execution of the processing phase. If the namespace was previously
empty (non-configured) and no new prep configs have been added, the
previous hash and new hash match and therefore the error message is not
patched on the namespace annotation, making it hard for a user to
understand why the new configuration is not being deployed.
=> Fix namespace fluentd status annotation update

config-reloader/controller/controller.go, config-reloader/generator/generator.go
The config files created by the config-reloader are never deleted.
This practically means that in environments with several namespaces
and/or a lot of creation/deletion of namespaces, a big number of files
of type `ns-<namespace>.conf` can end up populating the config
directory.
This fix adds a cleanup call at the end of each loop that verifies
whether any file belongs to namespaces that are no longer existent
and deletes them. This fix also deletes any configuration file
of namespaces that are still existent but have no specified fluentd
configuration.
=> Cleanup unused namespace configuration files

README.md, config-reloader/processors/processor.go, config-reloader/processors/thisns.go, config-reloader/processors/unique_rewrite_tag.go, config-reloader/processors/unique_rewrite_tag_test.go
The plugin "rewrite_tag_filter" provided alongside Fluentd allows conditional
tag rewriting to perform different processing pipelines based on log contents.
This same behavior is not achievable without it unless all logs are copied
to different output labels and then filtered through the grep plugin which
however introduces considerable overhead.
Clearly, however, the usage of this plugin needs to be constrained as it
allows to break the namespace isolation enforced by the config-reloader.
This enhancement introduces a new processor that allows to specify a new
virtual output plugin, "unique_rewrite_tag", which behaves exactly as the
"rewrite_tag_filter" (and has the same syntax and supported options), but
requires the new tag to be specified using the macro $tag(new_tag).
In order to …
=> Add new processor to allow controlled tag rewriting

README.md, config-reloader/config/config.go, config-reloader/generator/generator.go, config-reloader/processors/extract_plugins.go, config-reloader/templates/fluent.conf, log-router/templates/daemonset.yaml, log-router/values.yaml
The config-reloader assumes that the admin namespace in which fluentd configs get defined without validation and/or processing and in which virtual plugins are defined is the `kube-system` namespace. While this assumption is reasonable in general, there might be instances in which the logging infrastructure is installed in a dedicated namespace and it would be cleaner and more manageable to be able to install virtual plugins and global fluentd configs in that same namespace. Furthermore, it might be the case that the kube-system namespace already contains a number of infrastructural components that would benefit from having fluentd configurations defined using the config-reloader and that would also benefit from all the processing that the config-reloader can offer on those configs, such …
=> Make the admin namespace configurable

README.md
- Updated the `admin` configuration example to include the `match` directive to provide a fully working example for end-users. 
- The original example was misleading and incomplete.
Signed-off-by: SHAZAD BROHI <sbrohi@vmware.com>
=> Updated output plugin docs

charts/log-router/templates/daemonset.yaml, charts/log-router/templates/service.yaml, charts/log-router/templates/servicemonitor.yaml, charts/log-router/values.yaml, config-reloader/Gopkg.lock, config-reloader/config/config.go, config-reloader/generator/generator.go, config-reloader/main.go, config-reloader/metrics/metrics.go
Currently, when config-reloader fails to validate the fluentd configurations
for a given namespace, an error is logged and is attached to the namespace
via an annotation. This system, however, requires users to actively look
at namespace annotations or logs to ensure no errors are present whenever
a change in a fluentd configuration is deployed.
Users that are already utilizing Prometheus in their Kubernetes clusters,
are most likely measuring applications' stability via metrics and routing
alerts to a central location, where they are more visible.
This commit introduces the capability for config-reloader to expose its
own Prometheus metrics, which provide a simple boolean metric per
namespace exposing whether the fluentd configs in that namespace passed
validation or not.
These simple …
=> Expose config-reloader prometheus metrics

README.md, base-image/Dockerfile, charts/log-router/Chart.yaml
Update fluent-plugin-vmware-log-intelligence plugin to 2.0.4
Add fluent-plugin-mysqlslowquery which is a dependency of  fluent-plugin-vmware-log-intelligence
Update helm chart version to 0.3.5
Signed-off-by: Vivek Singh <svivekkumar@vmware.com>
=> Update log intelligence plugin to 2.0.4

base-image/Dockerfile, base-image/Gemfile
- update fluent-plugin-vmware-log-intelligence to 2.0.5
- version fluent-plugin-vmware-log-intelligence from rubygems (resolves #172)
=> chore: get vmware-log-intelligence from rubygems

charts/log-router/Chart.yaml, charts/log-router/templates/_helpers.tpl, charts/log-router/templates/sa.yaml, charts/log-router/values.yaml
Solves #160, #139 
Signed-off-by: Karan Kapoor <karan.kapoor@pega.com>
=> Adds support for SA annotations

config-reloader/config/config.go, config-reloader/fluentd/validator.go, config-reloader/fluentd/validator_test.go, config-reloader/generator/generator.go, config-reloader/main.go, config-reloader/util/util.go
Add timeout during exec for validate command of the config, so that it does not hang forever while validating
configuration. Also adds log on failure in validation of configs.
Signed-off-by: Vivek Singh <svivekkumar@vmware.com>
=> Add timeout and log for validation

CHANGELOG.md, README.md, base-image/Dockerfile
- Update changelogs file to be up-to-date to release v1.14.0-beta.2
- Remove go dep from build instructions (we use go modules)
- Fix minor errors in build instructions
- Add `tdnf upgrade -y` step to base-image Dockerfile
=> chore: update changelogs and couple fixes

base-image/Dockerfile
- upgrade to use photon:4.0
- upgrades systemd to 247 and enables l4z compression
- fixes #141
- resolves #184
=> chore(base-image): upgrade to use photon:4.0

base-image/Gemfile
- upgrade fluent-plugin-vmware-log-intelligence gem to v2.0.6 latest
=> chore: upgrade vmware-log-intelligence to 2.0.6

config-reloader/fluentd/reloader.go, config-reloader/fluentd/reloader_test.go
Move to gracefulReload endpoint to align with upstream docs after 1.9
Change failure to an error instead of info
Signed-off-by: Brian Davis <slimm609@gmail.com>
=> Move to graceful reload endpoint and error

config-reloader/main.go
- fix race condition when config-reloader start or restarts
- add a timeout default to 30 seconds, that is between 0 - 60 seconds based on cfg.ExecTimeoutSeconds
=> fix(config-reloader): add timeout seconds on startup

config-reloader/datasource/kube_informer.go, config-reloader/datasource/kubedatasource/configmap.go, config-reloader/datasource/kubedatasource/fluentdconfig.go
- sorts configs so they are ordered when compared to reduce reloads
- code from #158 and closes #158
=> feat(reloader): sorts configs so they are ordered

README.md, charts/log-router/Chart.yaml, charts/log-router/templates/daemonset.yaml, charts/log-router/values.yaml, config-reloader/Makefile, config-reloader/config/config.go, config-reloader/config/config_test.go, config-reloader/generator/generator.go, config-reloader/templates/fluent.conf
Solves #181
* Tested by changing to different log level which fluentd supports 
*  If loglevel provided is not supported then we fail with validation error. 
*  If log level is not provided then default logLevel `info` is used
Signed-off-by: Karan Kapoor karan.kapoor@pega.com
=> Make fluentd log level configurable

config-reloader/config/config.go
- modify validation on matadata values as they can have . char
- fixes #144
- fixes #98
=> fix(reloader): matadata/labels key can have a period .

base-image/Dockerfile, base-image/Gemfile
- use 1.0.0 vmware-loginsight gem from ruby gems
- remove fork gem building for loginsight gem
- this PR has merged https://github.com/vmware/fluent-plugin-vmware-loginsight/pull/24
=> chore(plugins): use loginsight gem 1.0.0

config-reloader/generator/generator.go, config-reloader/processors/destinations.go, config-reloader/processors/destinations_test.go, config-reloader/processors/detect_exceptions_test.go, config-reloader/processors/expand_tags_test.go, config-reloader/processors/extract_plugins_test.go, config-reloader/processors/labels.go, config-reloader/processors/labels_test.go, config-reloader/processors/mounted_file.go, config-reloader/processors/mounted_file_test.go, config-reloader/processors/processor.go, config-reloader/processors/processor_test.go, config-reloader/processors/relabel.go, config-reloader/processors/relabel_test.go, config-reloader/processors/share.go, config-reloader/processors/share_test.go, config-reloader/processors/thisns.go, config-reloader/processors/thisns_test.go, config-reloader/processors/unique_rewrite_tag.go, config-reloader/processors/unique_rewrite_tag_test.go
- fix the ctx.Namespace typo in ProcessorContext
=> fix(reloader): fix ctx.Namespace typo

charts/log-router/values.yaml
Typo in values.yaml `fluentdLog(L/l)evel` causes reloader container to fail:
```time="2021-04-21T16:11:02Z" level=info msg="Version: v1.14.0-2-ga41ec00"
time="2021-04-21T16:11:02Z" level=info msg="Config: &{Master: KubeConfig: FluentdRPCPort:24444 TemplatesDir:/templates OutputDir:/fluentd/etc LogLevel:debug FluentdLogLevel: AnnotConfigmapName:logging.csp.vmware.com/fluentd-configmap AnnotStatus:logging.csp.vmware.com/fluentd-status DefaultConfigmapName:fluentd-config IntervalSeconds:45 Datasource:default CRDMigrationMode:false FsDatasourceDir: AllowFile:false ID:kfo-log-router FluentdValidateCommand:/usr/local/bundle/bin/fluentd -p /fluentd/plugins MetaKey: MetaValues: LabelSelector: KubeletRoot:/var/lib/kubelet Namespaces:[] PrometheusEnabled:false MetricsPort:9000 …
```
=> Fix typo in values.yaml

config-reloader/templates/kubernetes.conf
- set `read_from_head` to `false` since k8s clusters do graceful log rotation
- in huge clusters, there is no need to read_from_head
- KFO takes a long time to read files from the beginning and still sends duplicate log lines
- since we are using .pos files and names do not collide, this should be safe
=> fix(kubernetes.conf): set read_from_head to false

config-reloader/templates/kubernetes.conf
- this reverts commit d92d41a2b4692c91af067c7d1cf9d05b556e205e.
- turns out setting `read_from_head true` is right behavior
=> Revert "fix(kubernetes.conf): set read_from_head to false"

base-image/Dockerfile, base-image/Gemfile, base-image/Gemfile.lock
- upgrade `fluentd` to new minor release [v1.13.1](https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#v1131)
- upgrade other non-pegged gems in Gemfile.lock
- upgrade `rdoc` to `>= 6.3.1` for CVE
=> chore(fluentd): upgrade fluentd v1.13.1 and gems

config-reloader/datasource/kube_informer.go
- resolves #222
- check for config status annotation before setting `IsKnowFromBefore` on each `nsconfig`
=> fix(generator): fix status annot on unused ns

config-reloader/datasource/kube_informer.go
- to use stategic merge patch for namespace annotations
=> fix: use strategic merge patch for namespace

config-reloader/datasource/kube_informer.go
This reverts commit 5f303eb137d97c9c37c016302fc229f5b4aa8046.
=> Revert "fix: use strategic merge patch for namespace"

config-reloader/datasource/datasource.go, config-reloader/datasource/kube_informer.go, config-reloader/generator/generator.go
- `IsKnownFromBefore` is useless logic in the `KubeInformer` code
=> fix(reloader): remove the IsKnowFromBefore logic

config-reloader/datasource/kube_informer.go
- multiple log-routers try to update a single unique ResourceVersion
- ignore errors.IsConflict as it is ResourceVersion collision
- no need to retry, each log-router is a process, muli-thread because of daemonset, etcd version is our lock
- only one log-router needs to succeed, same validation happens in all log-routers
=> fix(kube): ignore errors.IsConflict on update call

charts/log-router/Chart.yaml
- bump up chart version to `0.4.0` because of chart changes
=> feat(charts): bump up chart version to 0.4.0

README.md
I think is missing the `namespace` for annotate command.
=> Missing namespace in annotate cmd

base-image/Dockerfile
- upgrade ruby to version [2.7.4](https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released/)
=> chore(ruby): upgrade to ruby version 2.7.4

kubectl/manifests.yaml
- closes #261
- remove "patch" and add "update" on namespaces permissions
- helm is backwards-compatibile, kubectl manifests do not need to be
=> fix(kubectl): add update to kubectl manifests

config-reloader/templates/kubernetes.conf
- fixes issues in #290 for kubernetes in_tail timestamps
=> fix: fix datetime parse to extended format

config-reloader/controller/controller.go, config-reloader/datasource/fake.go, config-reloader/datasource/fs.go, config-reloader/datasource/kube_informer.go, config-reloader/go.mod, config-reloader/go.sum, config-reloader/util/util.go, config-reloader/util/util_test.go
- add kube pod informer for pods add/rm in namespace we monitor, rerun preprocess configs
- fixes #289
- fixes #253
- fixes issue with respecting `c.cfg.AnnotConfigmapName` on configmap namespaces discovery
- introduces `hashstructure` package for smarter hashing of changing objects
- make smarter hashing for `allConfigsHash` metahashing (without `reflect.DeepEqual()`)
=> fix: react to pod events to regen preprocess conf

config-reloader/templates/kubernetes.conf
If a log line is distributed over multiple lines in cri-o (partials) and it contains `{` and `}` the docker part seems to win (for the partial).
=> Fix cri-o Config when log line contains a json

config-reloader/generator/generator.go
Fix issue [302](https://github.com/vmware/kube-fluentd-operator/issues/302). Show error message when output is missing
=> Fix issue 302. Show error when dir is missing

config-reloader/datasource/kube_informer.go
Signed-off-by: vkadi <kadiyan.vandana@gmail.com>
=> Issue#289 Mounted file issue fix part-2

base-image/plugins/in_just_exit.rb
Fixes #105
Every time kube-fluentd-operator validates a fluentd config, it leaves behind a SERVERENGINE_SOCKETMANAGER socket file in /tmp.
```
ls -ltr /tmp
srwx------. 1 root root    0 Apr 16 00:03 SERVERENGINE_SOCKETMANAGER_2022-04-16T00:03:45Z_11491
srwx------. 1 root root    0 Apr 16 00:03 SERVERENGINE_SOCKETMANAGER_2022-04-16T00:03:46Z_11495
srwx------. 1 root root    0 Apr 16 00:03 SERVERENGINE_SOCKETMANAGER_2022-04-16T00:03:48Z_11499
srwx------. 1 root root    0 Apr 16 00:03 SERVERENGINE_SOCKETMANAGER_2022-04-16T00:03:49Z_11503
srwx------. 1 root root    0 Apr 16 00:03 SERVERENGINE_SOCKETMANAGER_2022-04-16T00:03:50Z_11505
```
The fix is to have just_exit plugin cleanup resources when it exists, so the socket files are not lingering.
The just_exit plugin can call …
=> Cleanup SERVERENGINE_SOCKETMANAGER socket files usually found in /tmp

base-image/Gemfile
It turns out the plugin requires gssapi to be present, so adding it as well.
=> Add webhdfs plugin

base-image/Gemfile, base-image/Gemfile.lock, config-reloader/controller/controller.go, config-reloader/datasource/fake.go, config-reloader/datasource/fs.go, config-reloader/datasource/kube_informer.go, config-reloader/go.mod, config-reloader/go.sum, config-reloader/util/util.go, config-reloader/util/util_test.go
Revert issue https://github.com/vmware/kube-fluentd-operator/issues/289 
The solution is not scalable for cluster with more than 10 nodes, it start to send a reload on rundeck every time a pod is change and increase without limit the fluentd memory. We will need to think a better solution for this. 
https://github.com/vmware/kube-fluentd-operator/pull/293
https://github.com/vmware/kube-fluentd-operator/pull/306
=> Revert issue big clusters

README.md
I am not positive, but if I am understanding things correctly, it seems like there is a . missing in the conversion of one of the labels examples.
Signed-off-by: David Dillon <djdillon@gmail.com>
=> README: Missing . in label expansion

config-reloader/datasource/kube_informer.go, config-reloader/datasource/kubedatasource/migrationmode.go
There is a small bug in #310 which gives always the error `"Failed to initialize the fluentdconfig crd client, d.fclient = nil"`.
=> Fix discovery of fluentdconfig if migration mode is enabled

base-image/entrypoint.sh, config-reloader/datasource/kubedatasource/fluentdconfig/crd/crd.go, config-reloader/fluentd/reloader.go, config-reloader/fluentd/reloader_test.go, config-reloader/templates/kubernetes-postprocess.conf, config-reloader/templates/kubernetes.conf, config-reloader/util/util_test.go
- fix reloader endpoint from post to get
- fix linting and test errors
- reduce time for sleep to check more often
- add skip_refresh_on_startup to support graceful reload as documented
=> fix: fix reloader endpoint from post to get

config-reloader/datasource/kube_informer.go
Set value to debug for pod change
=> feat: remove info logging for pod check

config-reloader/datasource/kube_informer.go, config-reloader/datasource/kubedatasource/configmap.go
Avoid use empty configmaps in fluentd
=> feat: avoid use empty configmaps

config-reloader/config/config.go, config-reloader/generator/generator.go, config-reloader/templates/kubernetes.conf
Include read_bytes_limit_per_second as parameter for in_tail plugin
=> feat: include read_bytes_limit_per_second as parameter

config-reloader/templates/kubernetes.conf
- add follow_inode to wildcard as recommended by the docs
```
Avoid to read rotated files duplicately. You should set true when you use * or strftime format in path.
```
=> fix: add follow_inode to wildcard

config-reloader/controller/controller.go, config-reloader/controller/controller_test.go, config-reloader/datasource/fs.go, config-reloader/fluentd/reloader.go, config-reloader/main.go, config-reloader/validate-logging-config.sh
- Move datasource case to main file
- Add test for controller
=> feat: add test for controller

base-image/Makefile, base-image/fluentd_test.go
- use local image instead of previous version
- fix docker localhost
=> fix: image tests

CHANGELOG.md, README.md
=> docs: new release version v1.18.1

Dockerfile, Makefile, config-reloader/fluentd/reloader.go, config-reloader/go.mod, config-reloader/go.sum, image/go.mod, image/go.sum
In case some old plugins are still in use `gracefulReload` may not work, preventing new configs to take effect.
=> fix: fallback to reload when gracefulReload fails

charts/log-router/templates/daemonset.yaml, charts/log-router/values.yaml
We had a control plane meltdown when starting KFO on a GKE cluster with 1000s of nodes as reloader will make several kube api calls at the same time when DaemonSet pods start at the same time. In order to mitigate this issue we are planning to go with `fs` datasource with configs read from a volume mount. But the current helm chart doesn't have an option to set required `--fs-dir` arg when `datasource: fs` is used. This PR is to add an option to set `fs-dir` in helm so that we can use `fs` datasoiurce.
=> Support setting fs-dir for fs datasource

config-reloader/datasource/kube_informer.go
Condition should be `!=` instead of `==` as logging is needed when `template.Render` fails.
=> Fix wrong conditional check
